import type { Metadata } from "next";
import "@src/styles/globals.css";
import AuthProvider from '../components/context/AuthProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background-tertiary "
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
